# Generated by Django 2.1.7 on 2019-03-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bd_date',
        ),
    ]
