# Generated by Django 2.1.7 on 2019-03-05 01:53

from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_remove_person_bd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bd_date',
            field=models.DateField(null=True, verbose_name=django.forms.widgets.SelectDateWidget),
        ),
    ]
